<?php

declare(strict_types=1);

use Infrangible\CatalogProductOptionProduct\Block\Adminhtml\Product\Edit\Tab\Options\Type\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Product $block */
/** @var Escaper $escaper */
?>

<script id="custom-option-image-type-template" type="text/x-magento-template">
    <div id="product_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset">
        <table class="data-table">
            <thead>
            <tr>
                <th class="col-sku"><?= $escaper->escapeHtml(__('SKU')); ?></th>
                <th class="col-scene"><?= $escaper->escapeHtml(__('Scene')); ?></th>
                <th class="col-images"><?= $escaper->escapeHtml(__('Images')); ?></th>
                <th class="col-image-format"><?= $escaper->escapeHtml(__('Product')); ?></th>
            </tr>
            </thead>
            <tr>
                <td>
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][sku]"
                           class="input-text type-sku"
                           value="<%- data.sku %>"
                           type="text">
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][scene]"
                           class="input-text type-scene"
                           value="<%- data.scene %>"
                           type="number">
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][images]"
                           class="input-text type-images"
                           value="<%- data.images %>"
                           type="number">
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][option_product_id]"
                           class="input-text type-option_product_id"
                           value="<%- data.option_product_id %>"
                           type="text">
                </td>
            </tr>
        </table>
    </div>
</script>
